remove unused methods of vmhooks
klever-io/klever-vm-executor-rs pull request #10
Opened 2024-10-28 00:25 UTC by 2yuri

2024-10-30 13:19 UTC, Beroni approved these changes

2024-10-31 12:15 UTC, marcioecom approved these changes

2024-11-01 12:06 UTC, fbsobreira requested changes

2024-11-01 12:06 UTC, fbsobreira commented on c-api/libvmexeccapi.h
> -  int32_t (*get_block_hash_func_ptr)(void *context, int64_t nonce, int32_t result_offset);
Don’t think this function should be removed…. how do you come with this? Block hash is a feature common used in several contracts

2024-11-04 11:54 UTC, closed without merging