Added handle for kda admin address
klever-io/klever-vm-executor-rs pull request #3
Opened 2024-05-21 18:50 UTC by yurilozorio

2024-05-21 18:51 UTC, fbsobreira submitted a review, later dismissed

2024-05-22 11:52 UTC, 2yuri requested changes
need to upgrade the cargo version, also needs to check the tests

2024-05-22 20:23 UTC, fbsobreira approved these changes, later dismissed

2024-05-22 20:47 UTC, 2yuri submitted a review, later dismissed

2024-05-22 21:00 UTC, fbsobreira approved these changes

2024-05-22 21:23 UTC, 2yuri approved these changes

2024-05-22 21:42 UTC, merged